//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ClienteEDD.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService1Soap", Namespace="http://tempuri.org/")]
    public partial class WebService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback VerifiCarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback CambiarEstadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback CargarUsuariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetornarCorreoOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetornarClaveOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExisteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertarListaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerarArbolitoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerarEspejoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerarTableroOperationCompleted;
        
        private System.Threading.SendOrPostCallback MeterMatrizOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarConfiguracionOperationCompleted;
        
        private System.Threading.SendOrPostCallback CargarConfiguracionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConvertirArbolOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConvertirEspejoOperationCompleted;
        
        private System.Threading.SendOrPostCallback DatosArbolOperationCompleted;
        
        private System.Threading.SendOrPostCallback HacerTableroL0OperationCompleted;
        
        private System.Threading.SendOrPostCallback HacerTableroL1OperationCompleted;
        
        private System.Threading.SendOrPostCallback HacerTableroL2OperationCompleted;
        
        private System.Threading.SendOrPostCallback HacerTableroL3OperationCompleted;
        
        private System.Threading.SendOrPostCallback GanadosOperationCompleted;
        
        private System.Threading.SendOrPostCallback PromOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService1() {
            this.Url = global::ClienteEDD.Properties.Settings.Default.ClienteEDD_localhost_WebService1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event VerifiCarUsuarioCompletedEventHandler VerifiCarUsuarioCompleted;
        
        /// <remarks/>
        public event CambiarEstadoCompletedEventHandler CambiarEstadoCompleted;
        
        /// <remarks/>
        public event InsertarUsuarioCompletedEventHandler InsertarUsuarioCompleted;
        
        /// <remarks/>
        public event CargarUsuariosCompletedEventHandler CargarUsuariosCompleted;
        
        /// <remarks/>
        public event RetornarCorreoCompletedEventHandler RetornarCorreoCompleted;
        
        /// <remarks/>
        public event RetornarClaveCompletedEventHandler RetornarClaveCompleted;
        
        /// <remarks/>
        public event ExisteCompletedEventHandler ExisteCompleted;
        
        /// <remarks/>
        public event ModificarUsuarioCompletedEventHandler ModificarUsuarioCompleted;
        
        /// <remarks/>
        public event EliminarUsuarioCompletedEventHandler EliminarUsuarioCompleted;
        
        /// <remarks/>
        public event InsertarListaCompletedEventHandler InsertarListaCompleted;
        
        /// <remarks/>
        public event GenerarArbolitoCompletedEventHandler GenerarArbolitoCompleted;
        
        /// <remarks/>
        public event GenerarEspejoCompletedEventHandler GenerarEspejoCompleted;
        
        /// <remarks/>
        public event GenerarTableroCompletedEventHandler GenerarTableroCompleted;
        
        /// <remarks/>
        public event MeterMatrizCompletedEventHandler MeterMatrizCompleted;
        
        /// <remarks/>
        public event GuardarConfiguracionCompletedEventHandler GuardarConfiguracionCompleted;
        
        /// <remarks/>
        public event CargarConfiguracionCompletedEventHandler CargarConfiguracionCompleted;
        
        /// <remarks/>
        public event ConvertirArbolCompletedEventHandler ConvertirArbolCompleted;
        
        /// <remarks/>
        public event ConvertirEspejoCompletedEventHandler ConvertirEspejoCompleted;
        
        /// <remarks/>
        public event DatosArbolCompletedEventHandler DatosArbolCompleted;
        
        /// <remarks/>
        public event HacerTableroL0CompletedEventHandler HacerTableroL0Completed;
        
        /// <remarks/>
        public event HacerTableroL1CompletedEventHandler HacerTableroL1Completed;
        
        /// <remarks/>
        public event HacerTableroL2CompletedEventHandler HacerTableroL2Completed;
        
        /// <remarks/>
        public event HacerTableroL3CompletedEventHandler HacerTableroL3Completed;
        
        /// <remarks/>
        public event GanadosCompletedEventHandler GanadosCompleted;
        
        /// <remarks/>
        public event PromCompletedEventHandler PromCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerifiCarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool VerifiCarUsuario(string nickname, string Contrasena) {
            object[] results = this.Invoke("VerifiCarUsuario", new object[] {
                        nickname,
                        Contrasena});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void VerifiCarUsuarioAsync(string nickname, string Contrasena) {
            this.VerifiCarUsuarioAsync(nickname, Contrasena, null);
        }
        
        /// <remarks/>
        public void VerifiCarUsuarioAsync(string nickname, string Contrasena, object userState) {
            if ((this.VerifiCarUsuarioOperationCompleted == null)) {
                this.VerifiCarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerifiCarUsuarioOperationCompleted);
            }
            this.InvokeAsync("VerifiCarUsuario", new object[] {
                        nickname,
                        Contrasena}, this.VerifiCarUsuarioOperationCompleted, userState);
        }
        
        private void OnVerifiCarUsuarioOperationCompleted(object arg) {
            if ((this.VerifiCarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerifiCarUsuarioCompleted(this, new VerifiCarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CambiarEstado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CambiarEstado(string nickname) {
            this.Invoke("CambiarEstado", new object[] {
                        nickname});
        }
        
        /// <remarks/>
        public void CambiarEstadoAsync(string nickname) {
            this.CambiarEstadoAsync(nickname, null);
        }
        
        /// <remarks/>
        public void CambiarEstadoAsync(string nickname, object userState) {
            if ((this.CambiarEstadoOperationCompleted == null)) {
                this.CambiarEstadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCambiarEstadoOperationCompleted);
            }
            this.InvokeAsync("CambiarEstado", new object[] {
                        nickname}, this.CambiarEstadoOperationCompleted, userState);
        }
        
        private void OnCambiarEstadoOperationCompleted(object arg) {
            if ((this.CambiarEstadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CambiarEstadoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsertarUsuario(string nickname, string contrasena, string correo) {
            object[] results = this.Invoke("InsertarUsuario", new object[] {
                        nickname,
                        contrasena,
                        correo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void InsertarUsuarioAsync(string nickname, string contrasena, string correo) {
            this.InsertarUsuarioAsync(nickname, contrasena, correo, null);
        }
        
        /// <remarks/>
        public void InsertarUsuarioAsync(string nickname, string contrasena, string correo, object userState) {
            if ((this.InsertarUsuarioOperationCompleted == null)) {
                this.InsertarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertarUsuarioOperationCompleted);
            }
            this.InvokeAsync("InsertarUsuario", new object[] {
                        nickname,
                        contrasena,
                        correo}, this.InsertarUsuarioOperationCompleted, userState);
        }
        
        private void OnInsertarUsuarioOperationCompleted(object arg) {
            if ((this.InsertarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertarUsuarioCompleted(this, new InsertarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CargarUsuarios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CargarUsuarios() {
            object[] results = this.Invoke("CargarUsuarios", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CargarUsuariosAsync() {
            this.CargarUsuariosAsync(null);
        }
        
        /// <remarks/>
        public void CargarUsuariosAsync(object userState) {
            if ((this.CargarUsuariosOperationCompleted == null)) {
                this.CargarUsuariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCargarUsuariosOperationCompleted);
            }
            this.InvokeAsync("CargarUsuarios", new object[0], this.CargarUsuariosOperationCompleted, userState);
        }
        
        private void OnCargarUsuariosOperationCompleted(object arg) {
            if ((this.CargarUsuariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CargarUsuariosCompleted(this, new CargarUsuariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetornarCorreo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RetornarCorreo(string nombre) {
            object[] results = this.Invoke("RetornarCorreo", new object[] {
                        nombre});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RetornarCorreoAsync(string nombre) {
            this.RetornarCorreoAsync(nombre, null);
        }
        
        /// <remarks/>
        public void RetornarCorreoAsync(string nombre, object userState) {
            if ((this.RetornarCorreoOperationCompleted == null)) {
                this.RetornarCorreoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetornarCorreoOperationCompleted);
            }
            this.InvokeAsync("RetornarCorreo", new object[] {
                        nombre}, this.RetornarCorreoOperationCompleted, userState);
        }
        
        private void OnRetornarCorreoOperationCompleted(object arg) {
            if ((this.RetornarCorreoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetornarCorreoCompleted(this, new RetornarCorreoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetornarClave", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RetornarClave(string nombre) {
            object[] results = this.Invoke("RetornarClave", new object[] {
                        nombre});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RetornarClaveAsync(string nombre) {
            this.RetornarClaveAsync(nombre, null);
        }
        
        /// <remarks/>
        public void RetornarClaveAsync(string nombre, object userState) {
            if ((this.RetornarClaveOperationCompleted == null)) {
                this.RetornarClaveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetornarClaveOperationCompleted);
            }
            this.InvokeAsync("RetornarClave", new object[] {
                        nombre}, this.RetornarClaveOperationCompleted, userState);
        }
        
        private void OnRetornarClaveOperationCompleted(object arg) {
            if ((this.RetornarClaveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetornarClaveCompleted(this, new RetornarClaveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Existe", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Existe(string nickname) {
            object[] results = this.Invoke("Existe", new object[] {
                        nickname});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ExisteAsync(string nickname) {
            this.ExisteAsync(nickname, null);
        }
        
        /// <remarks/>
        public void ExisteAsync(string nickname, object userState) {
            if ((this.ExisteOperationCompleted == null)) {
                this.ExisteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExisteOperationCompleted);
            }
            this.InvokeAsync("Existe", new object[] {
                        nickname}, this.ExisteOperationCompleted, userState);
        }
        
        private void OnExisteOperationCompleted(object arg) {
            if ((this.ExisteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExisteCompleted(this, new ExisteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ModificarUsuario(string nickname, string nuevonickname, string correo, string contrasena) {
            object[] results = this.Invoke("ModificarUsuario", new object[] {
                        nickname,
                        nuevonickname,
                        correo,
                        contrasena});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ModificarUsuarioAsync(string nickname, string nuevonickname, string correo, string contrasena) {
            this.ModificarUsuarioAsync(nickname, nuevonickname, correo, contrasena, null);
        }
        
        /// <remarks/>
        public void ModificarUsuarioAsync(string nickname, string nuevonickname, string correo, string contrasena, object userState) {
            if ((this.ModificarUsuarioOperationCompleted == null)) {
                this.ModificarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarUsuarioOperationCompleted);
            }
            this.InvokeAsync("ModificarUsuario", new object[] {
                        nickname,
                        nuevonickname,
                        correo,
                        contrasena}, this.ModificarUsuarioOperationCompleted, userState);
        }
        
        private void OnModificarUsuarioOperationCompleted(object arg) {
            if ((this.ModificarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarUsuarioCompleted(this, new ModificarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EliminarUsuario(string nickname) {
            object[] results = this.Invoke("EliminarUsuario", new object[] {
                        nickname});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarUsuarioAsync(string nickname) {
            this.EliminarUsuarioAsync(nickname, null);
        }
        
        /// <remarks/>
        public void EliminarUsuarioAsync(string nickname, object userState) {
            if ((this.EliminarUsuarioOperationCompleted == null)) {
                this.EliminarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarUsuarioOperationCompleted);
            }
            this.InvokeAsync("EliminarUsuario", new object[] {
                        nickname}, this.EliminarUsuarioOperationCompleted, userState);
        }
        
        private void OnEliminarUsuarioOperationCompleted(object arg) {
            if ((this.EliminarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarUsuarioCompleted(this, new EliminarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertarLista", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InsertarLista(string UsuarioBase, string oponent, int Udesple, int Usobre, int Udestrui, int gano) {
            this.Invoke("InsertarLista", new object[] {
                        UsuarioBase,
                        oponent,
                        Udesple,
                        Usobre,
                        Udestrui,
                        gano});
        }
        
        /// <remarks/>
        public void InsertarListaAsync(string UsuarioBase, string oponent, int Udesple, int Usobre, int Udestrui, int gano) {
            this.InsertarListaAsync(UsuarioBase, oponent, Udesple, Usobre, Udestrui, gano, null);
        }
        
        /// <remarks/>
        public void InsertarListaAsync(string UsuarioBase, string oponent, int Udesple, int Usobre, int Udestrui, int gano, object userState) {
            if ((this.InsertarListaOperationCompleted == null)) {
                this.InsertarListaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertarListaOperationCompleted);
            }
            this.InvokeAsync("InsertarLista", new object[] {
                        UsuarioBase,
                        oponent,
                        Udesple,
                        Usobre,
                        Udestrui,
                        gano}, this.InsertarListaOperationCompleted, userState);
        }
        
        private void OnInsertarListaOperationCompleted(object arg) {
            if ((this.InsertarListaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertarListaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GenerarArbolito", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GenerarArbolito() {
            this.Invoke("GenerarArbolito", new object[0]);
        }
        
        /// <remarks/>
        public void GenerarArbolitoAsync() {
            this.GenerarArbolitoAsync(null);
        }
        
        /// <remarks/>
        public void GenerarArbolitoAsync(object userState) {
            if ((this.GenerarArbolitoOperationCompleted == null)) {
                this.GenerarArbolitoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerarArbolitoOperationCompleted);
            }
            this.InvokeAsync("GenerarArbolito", new object[0], this.GenerarArbolitoOperationCompleted, userState);
        }
        
        private void OnGenerarArbolitoOperationCompleted(object arg) {
            if ((this.GenerarArbolitoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerarArbolitoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GenerarEspejo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GenerarEspejo() {
            this.Invoke("GenerarEspejo", new object[0]);
        }
        
        /// <remarks/>
        public void GenerarEspejoAsync() {
            this.GenerarEspejoAsync(null);
        }
        
        /// <remarks/>
        public void GenerarEspejoAsync(object userState) {
            if ((this.GenerarEspejoOperationCompleted == null)) {
                this.GenerarEspejoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerarEspejoOperationCompleted);
            }
            this.InvokeAsync("GenerarEspejo", new object[0], this.GenerarEspejoOperationCompleted, userState);
        }
        
        private void OnGenerarEspejoOperationCompleted(object arg) {
            if ((this.GenerarEspejoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerarEspejoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GenerarTablero", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GenerarTablero() {
            this.Invoke("GenerarTablero", new object[0]);
        }
        
        /// <remarks/>
        public void GenerarTableroAsync() {
            this.GenerarTableroAsync(null);
        }
        
        /// <remarks/>
        public void GenerarTableroAsync(object userState) {
            if ((this.GenerarTableroOperationCompleted == null)) {
                this.GenerarTableroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerarTableroOperationCompleted);
            }
            this.InvokeAsync("GenerarTablero", new object[0], this.GenerarTableroOperationCompleted, userState);
        }
        
        private void OnGenerarTableroOperationCompleted(object arg) {
            if ((this.GenerarTableroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerarTableroCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MeterMatriz", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool MeterMatriz(string jugador, string columna, int fila, string unidad, int vivo) {
            object[] results = this.Invoke("MeterMatriz", new object[] {
                        jugador,
                        columna,
                        fila,
                        unidad,
                        vivo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void MeterMatrizAsync(string jugador, string columna, int fila, string unidad, int vivo) {
            this.MeterMatrizAsync(jugador, columna, fila, unidad, vivo, null);
        }
        
        /// <remarks/>
        public void MeterMatrizAsync(string jugador, string columna, int fila, string unidad, int vivo, object userState) {
            if ((this.MeterMatrizOperationCompleted == null)) {
                this.MeterMatrizOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMeterMatrizOperationCompleted);
            }
            this.InvokeAsync("MeterMatriz", new object[] {
                        jugador,
                        columna,
                        fila,
                        unidad,
                        vivo}, this.MeterMatrizOperationCompleted, userState);
        }
        
        private void OnMeterMatrizOperationCompleted(object arg) {
            if ((this.MeterMatrizCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MeterMatrizCompleted(this, new MeterMatrizCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GuardarConfiguracion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GuardarConfiguracion(string jugador1, string jugador2, int n1, int n2, int n3, int n4, int tamx, int tamy, int tipo, string ho) {
            this.Invoke("GuardarConfiguracion", new object[] {
                        jugador1,
                        jugador2,
                        n1,
                        n2,
                        n3,
                        n4,
                        tamx,
                        tamy,
                        tipo,
                        ho});
        }
        
        /// <remarks/>
        public void GuardarConfiguracionAsync(string jugador1, string jugador2, int n1, int n2, int n3, int n4, int tamx, int tamy, int tipo, string ho) {
            this.GuardarConfiguracionAsync(jugador1, jugador2, n1, n2, n3, n4, tamx, tamy, tipo, ho, null);
        }
        
        /// <remarks/>
        public void GuardarConfiguracionAsync(string jugador1, string jugador2, int n1, int n2, int n3, int n4, int tamx, int tamy, int tipo, string ho, object userState) {
            if ((this.GuardarConfiguracionOperationCompleted == null)) {
                this.GuardarConfiguracionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarConfiguracionOperationCompleted);
            }
            this.InvokeAsync("GuardarConfiguracion", new object[] {
                        jugador1,
                        jugador2,
                        n1,
                        n2,
                        n3,
                        n4,
                        tamx,
                        tamy,
                        tipo,
                        ho}, this.GuardarConfiguracionOperationCompleted, userState);
        }
        
        private void OnGuardarConfiguracionOperationCompleted(object arg) {
            if ((this.GuardarConfiguracionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarConfiguracionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CargarConfiguracion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CargarConfiguracion() {
            object[] results = this.Invoke("CargarConfiguracion", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CargarConfiguracionAsync() {
            this.CargarConfiguracionAsync(null);
        }
        
        /// <remarks/>
        public void CargarConfiguracionAsync(object userState) {
            if ((this.CargarConfiguracionOperationCompleted == null)) {
                this.CargarConfiguracionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCargarConfiguracionOperationCompleted);
            }
            this.InvokeAsync("CargarConfiguracion", new object[0], this.CargarConfiguracionOperationCompleted, userState);
        }
        
        private void OnCargarConfiguracionOperationCompleted(object arg) {
            if ((this.CargarConfiguracionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CargarConfiguracionCompleted(this, new CargarConfiguracionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConvertirArbol", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConvertirArbol(string archivo) {
            object[] results = this.Invoke("ConvertirArbol", new object[] {
                        archivo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConvertirArbolAsync(string archivo) {
            this.ConvertirArbolAsync(archivo, null);
        }
        
        /// <remarks/>
        public void ConvertirArbolAsync(string archivo, object userState) {
            if ((this.ConvertirArbolOperationCompleted == null)) {
                this.ConvertirArbolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConvertirArbolOperationCompleted);
            }
            this.InvokeAsync("ConvertirArbol", new object[] {
                        archivo}, this.ConvertirArbolOperationCompleted, userState);
        }
        
        private void OnConvertirArbolOperationCompleted(object arg) {
            if ((this.ConvertirArbolCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConvertirArbolCompleted(this, new ConvertirArbolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConvertirEspejo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConvertirEspejo(string archivo) {
            object[] results = this.Invoke("ConvertirEspejo", new object[] {
                        archivo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConvertirEspejoAsync(string archivo) {
            this.ConvertirEspejoAsync(archivo, null);
        }
        
        /// <remarks/>
        public void ConvertirEspejoAsync(string archivo, object userState) {
            if ((this.ConvertirEspejoOperationCompleted == null)) {
                this.ConvertirEspejoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConvertirEspejoOperationCompleted);
            }
            this.InvokeAsync("ConvertirEspejo", new object[] {
                        archivo}, this.ConvertirEspejoOperationCompleted, userState);
        }
        
        private void OnConvertirEspejoOperationCompleted(object arg) {
            if ((this.ConvertirEspejoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConvertirEspejoCompleted(this, new ConvertirEspejoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DatosArbol", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DatosArbol() {
            object[] results = this.Invoke("DatosArbol", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DatosArbolAsync() {
            this.DatosArbolAsync(null);
        }
        
        /// <remarks/>
        public void DatosArbolAsync(object userState) {
            if ((this.DatosArbolOperationCompleted == null)) {
                this.DatosArbolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDatosArbolOperationCompleted);
            }
            this.InvokeAsync("DatosArbol", new object[0], this.DatosArbolOperationCompleted, userState);
        }
        
        private void OnDatosArbolOperationCompleted(object arg) {
            if ((this.DatosArbolCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DatosArbolCompleted(this, new DatosArbolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HacerTableroL0", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HacerTableroL0(string archivo) {
            object[] results = this.Invoke("HacerTableroL0", new object[] {
                        archivo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HacerTableroL0Async(string archivo) {
            this.HacerTableroL0Async(archivo, null);
        }
        
        /// <remarks/>
        public void HacerTableroL0Async(string archivo, object userState) {
            if ((this.HacerTableroL0OperationCompleted == null)) {
                this.HacerTableroL0OperationCompleted = new System.Threading.SendOrPostCallback(this.OnHacerTableroL0OperationCompleted);
            }
            this.InvokeAsync("HacerTableroL0", new object[] {
                        archivo}, this.HacerTableroL0OperationCompleted, userState);
        }
        
        private void OnHacerTableroL0OperationCompleted(object arg) {
            if ((this.HacerTableroL0Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HacerTableroL0Completed(this, new HacerTableroL0CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HacerTableroL1", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HacerTableroL1(string archivo) {
            object[] results = this.Invoke("HacerTableroL1", new object[] {
                        archivo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HacerTableroL1Async(string archivo) {
            this.HacerTableroL1Async(archivo, null);
        }
        
        /// <remarks/>
        public void HacerTableroL1Async(string archivo, object userState) {
            if ((this.HacerTableroL1OperationCompleted == null)) {
                this.HacerTableroL1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnHacerTableroL1OperationCompleted);
            }
            this.InvokeAsync("HacerTableroL1", new object[] {
                        archivo}, this.HacerTableroL1OperationCompleted, userState);
        }
        
        private void OnHacerTableroL1OperationCompleted(object arg) {
            if ((this.HacerTableroL1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HacerTableroL1Completed(this, new HacerTableroL1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HacerTableroL2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HacerTableroL2(string archivo) {
            object[] results = this.Invoke("HacerTableroL2", new object[] {
                        archivo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HacerTableroL2Async(string archivo) {
            this.HacerTableroL2Async(archivo, null);
        }
        
        /// <remarks/>
        public void HacerTableroL2Async(string archivo, object userState) {
            if ((this.HacerTableroL2OperationCompleted == null)) {
                this.HacerTableroL2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnHacerTableroL2OperationCompleted);
            }
            this.InvokeAsync("HacerTableroL2", new object[] {
                        archivo}, this.HacerTableroL2OperationCompleted, userState);
        }
        
        private void OnHacerTableroL2OperationCompleted(object arg) {
            if ((this.HacerTableroL2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HacerTableroL2Completed(this, new HacerTableroL2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HacerTableroL3", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HacerTableroL3(string archivo) {
            object[] results = this.Invoke("HacerTableroL3", new object[] {
                        archivo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HacerTableroL3Async(string archivo) {
            this.HacerTableroL3Async(archivo, null);
        }
        
        /// <remarks/>
        public void HacerTableroL3Async(string archivo, object userState) {
            if ((this.HacerTableroL3OperationCompleted == null)) {
                this.HacerTableroL3OperationCompleted = new System.Threading.SendOrPostCallback(this.OnHacerTableroL3OperationCompleted);
            }
            this.InvokeAsync("HacerTableroL3", new object[] {
                        archivo}, this.HacerTableroL3OperationCompleted, userState);
        }
        
        private void OnHacerTableroL3OperationCompleted(object arg) {
            if ((this.HacerTableroL3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HacerTableroL3Completed(this, new HacerTableroL3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Ganados", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Ganados() {
            object[] results = this.Invoke("Ganados", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GanadosAsync() {
            this.GanadosAsync(null);
        }
        
        /// <remarks/>
        public void GanadosAsync(object userState) {
            if ((this.GanadosOperationCompleted == null)) {
                this.GanadosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGanadosOperationCompleted);
            }
            this.InvokeAsync("Ganados", new object[0], this.GanadosOperationCompleted, userState);
        }
        
        private void OnGanadosOperationCompleted(object arg) {
            if ((this.GanadosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GanadosCompleted(this, new GanadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Prom", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Prom() {
            object[] results = this.Invoke("Prom", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PromAsync() {
            this.PromAsync(null);
        }
        
        /// <remarks/>
        public void PromAsync(object userState) {
            if ((this.PromOperationCompleted == null)) {
                this.PromOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPromOperationCompleted);
            }
            this.InvokeAsync("Prom", new object[0], this.PromOperationCompleted, userState);
        }
        
        private void OnPromOperationCompleted(object arg) {
            if ((this.PromCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PromCompleted(this, new PromCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void VerifiCarUsuarioCompletedEventHandler(object sender, VerifiCarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerifiCarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerifiCarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void CambiarEstadoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void InsertarUsuarioCompletedEventHandler(object sender, InsertarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void CargarUsuariosCompletedEventHandler(object sender, CargarUsuariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CargarUsuariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CargarUsuariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void RetornarCorreoCompletedEventHandler(object sender, RetornarCorreoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetornarCorreoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetornarCorreoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void RetornarClaveCompletedEventHandler(object sender, RetornarClaveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetornarClaveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetornarClaveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ExisteCompletedEventHandler(object sender, ExisteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExisteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExisteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ModificarUsuarioCompletedEventHandler(object sender, ModificarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModificarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModificarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void EliminarUsuarioCompletedEventHandler(object sender, EliminarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void InsertarListaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GenerarArbolitoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GenerarEspejoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GenerarTableroCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void MeterMatrizCompletedEventHandler(object sender, MeterMatrizCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MeterMatrizCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MeterMatrizCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GuardarConfiguracionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void CargarConfiguracionCompletedEventHandler(object sender, CargarConfiguracionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CargarConfiguracionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CargarConfiguracionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ConvertirArbolCompletedEventHandler(object sender, ConvertirArbolCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConvertirArbolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConvertirArbolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ConvertirEspejoCompletedEventHandler(object sender, ConvertirEspejoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConvertirEspejoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConvertirEspejoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void DatosArbolCompletedEventHandler(object sender, DatosArbolCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DatosArbolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DatosArbolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void HacerTableroL0CompletedEventHandler(object sender, HacerTableroL0CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HacerTableroL0CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HacerTableroL0CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void HacerTableroL1CompletedEventHandler(object sender, HacerTableroL1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HacerTableroL1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HacerTableroL1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void HacerTableroL2CompletedEventHandler(object sender, HacerTableroL2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HacerTableroL2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HacerTableroL2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void HacerTableroL3CompletedEventHandler(object sender, HacerTableroL3CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HacerTableroL3CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HacerTableroL3CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GanadosCompletedEventHandler(object sender, GanadosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GanadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GanadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void PromCompletedEventHandler(object sender, PromCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PromCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PromCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591